### ISSUE TITLE
Installing the plugin with Active Directory

### ISSUE THREAD

**Issue by terdinatore** [Monogramm/MauticLdapAuthBundle#1]
First of all, I want to thank the author for providing this plugin, which has been the main reason for me to start using Mautic, which is a truly awesome software.

I have tried to get your plugin working for authentication with an Active Directory Server over the last two days.

For someone who reads this who knows as much as I did two days ago, I want to sum up quickly what ways there are to install Mautic and what the occuring problems were for me.

**1. Docker Mautic :** 
I started to deploy Mautic with docker-compose using the Docker Hub Mautic image, which works fine when not using this plugin. Docker images are difficult to modify when you do not build them yourself. To install the missing dependencies for the LDAP plugin, namely `php/ext-ldap` and `symfony/ldap`, I tried to build my own Docker image using my own Gitlab registry. I failed to inlcude `symfony/ldap` in my image and stopped.
  Problems: 
a. Before you can install the plugin with composer you will need to increase the `memory-limit` in `mautic-php.ini` (docker-only file)
 b. Executing composer require monogramm/mautic-ldapauth-bundle will break your install resulting in the following error because it also changes files outside the plugin: 
```
Fatal error: Uncaught Error: Class 'Mautic\CoreBundle\ErrorHandler\ErrorHandler' not found in /var/www/html/index.php:29 
Stack trace: #0 {main} thrown in /var/www/html/index.php on line 29
```
c. Install with ZIP file: Since the dependencies are not installed, specifically symfony/ldap, which requires php7.1-ldap extension, you will hit this error: 
```
[2019-04-25 15:11:07] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "LdapClient" from namespace "Symfony\Component\Ldap". 
Did you forget a "use" statement for another namespace?" at /var/www/html/plugins/MauticLdapAuthBundle/Integration/LdapAuthIntegration.php line 122 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): 
Attempted to load class \"LdapClient\" from namespace \"Symfony\\Component\\Ldap\".
Did you forget a \"use\" statement for another namespace? at /var/www/html/plugins/MauticLdapAuthBundle/Integration/LdapAuthIntegration.php:122)"} []
```
**2. Mautic Production Install :** 
One can install a “preconfigured” Mautic from mautic.org/download. This is basically the same install as if pulled with docker. Both share the same problem: They are not built with composer which results in the same problems as before. 

**3. Development install** as advised on github.com/mautic/mautic : 
This is most likely how the author intended the plugin be installed. Running `composer require` does work here without ruining your install, but:
 a. Bundle gets a wrong name on install, easily fixed by `$ cd plugins` `$ mv MauticLdapauthBundle/ MauticLdapAuthBundle/`
One can then load and enable the plugin in the browser and configure the options in `app/config/local.php`

So after renaming the plugin and manually deleting the cache a few times (`rm -rf app/cache/prod/*`) I am able to get this error on login: `LDAP authentication problem; Invalid credentials`
I think this is a partial success since the plugin seems to work this way and there probably is an error in my config below.

This is what my config non working looks like:
```
        'ldap_auth_host' => '10.1.25.10',
        'ldap_auth_port' => 389,
        'ldap_auth_version' => 3,
        'ldap_auth_ssl' => false,
        'ldap_auth_starttls' => false,
        'ldap_auth_base_dn' => 'cn=Users,dc=my,dc=domain,dc=name',
        'ldap_auth_user_query' => '(objectclass=user)',
        'ldap_auth_username_attribute' => 'sAMAccountName',
        'ldap_auth_email_attribute' => 'mail',
        'ldap_auth_firstname_attribute' => 'givenname',
        'ldap_auth_lastname_attribute' => 'sn',
        'ldap_auth_fullname_attribute' => 'displayname’, 
```

Perhaps the author might find the errors in my config and can make changes to the code to allow the plugin to be used with docker or an production install. Personally, I am only able to test the code.

PS: What did screw up every installation I made is the following command: `php app/console cache:clear --env=prod` Deleting the content of `./app/cache/prod/*` manually worked fine though.

**Comment by madmath03** [comment]
Well, as the CTO of my company and author of this plugin, I am very pleased to see you enjoy it 😃 
I also feel kind of sorry that you spent 2 days working on it as I feel we could have provided you the help that you needed to get it working almost instantly (see later).

You are absolutely right in saying that without composer, you will need to manually install symfony/ldap and all its requirements, making the official docker image or production bundle unusable.
This is actually something we reported to the Mautic official docker image but still waiting for an answer: mautic/docker-mautic#95

Modifying this plugin to not require `symfony/ldap` would be possible and we even started developing it like that... but that meant making all the LDAP calls and error management by hand, making it a lot harder to maintain. 
This is why we went with Symfony ldap client which eases the development and we are not going to change that... but that does not mean that the "development" install is what we aim for : we are using lots of Open Source projects and contribute or build production ready docker images for those projects, and Mautic is not an exception.

Due to the current limitations of the official image, we built our own docker images : 
* [Monogramm/docker-mautic-base](https://github.com/Monogramm/docker-mautic-base) : fork of official image to contribute and send PR, with a `develop` branch merging all WIP contributions we sent and available as `monogramm/docker-mautic-base` on DockerHub
* [Monogramm/docker-mautic](https://github.com/Monogramm/docker-mautic) : our custom image based on `monogramm/docker-mautic-base` and adding LDAP requirements and this LdapAuthBundle, and available as `monogramm/docker-mautic` on [DockerHub](https://hub.docker.com/r/monogramm/docker-mautic/)

Regarding your config, I do not see anything particularly wrong but we've only tested this plugin with OpenLDAP, not Active Directory, so there might be some surprises.
While you still are in a development environment, I suggest you use symfony development mode by accessing mautic at `index_dev.php` : this will give you useful information like the logs and actions called and might help you to find out the correct configuration.

Once you find out the correct configuration for your AD, I suggest you give another try at using docker-compose but with our docker image instead.

I will try to find some time to add in the README a link to our docker image packaging this plugin, and specify that zip install requires to manually install symfony/ldap, hoping it will prevent others to spend 2 days configuring it 😉

**Comment by terdinatore** [comment]
Thank you, madmath03 for answering at this speed! I can see you are working hard to improve Mautic.

I completely agree with not "reinventing the wheel" when you use symfony/ldap. I also noticed that mautic uses a deprecated version of Symfony, this certainly does not help developing on Mautic, too.

I have also tried your custom docker container now but it also does not install your plugin for me automatically. To be fair, I did not manage to build a docker container that did not need a lot of tinkering after being built, either. 

Unfortunately, after I managed to get a working docker dev environment, when I prepended the login URL with `index_dev.php` it went back to `Invalid login` from `LDAP authentication problem`. So no additional information from there

Of course, I cannot not tell if this are issues caused by my errors or if there is an actual problem with the plugin as long as I do not have step-by-step instruction from your side to compare. I would be very grateful if you could find the time to elaborate on that.

I have attached my current Dockerfile based of the official docker-mautic-apache:
[docker-entrypoint.sh.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124022/docker-entrypoint.sh.txt)
[Dockerfile.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124023/Dockerfile.txt)
[makeconfig.php.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124024/makeconfig.php.txt)
[makedb.php.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124025/makedb.php.txt)
[mautic-php.ini.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124026/mautic-php.ini.txt)
[mautic.crontab.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124027/mautic.crontab.txt)
[docker-compose.yml.txt](https://github.com/Monogramm/MauticLdapAuthBundle/files/3124036/docker-compose.yml.txt)

 To get this working I needed execute the following commands in the container after `docker-compose up`:
```
composer install
mkdir app/cache/prod
composer require monogramm/mautic-ldapauth-bundle
mv MauticLdapauthBundle/ MauticLdapAuthBundle/
chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
rm -rf app/cache/prod/*```

**Comment by madmath03** [comment]
Hello @terdinatore ,

Sorry for the late reply.
Even if our docker container is still in its early stages of development, I was concerned about the fact you mentioned that you could not install this plugin in it...

After investigating, I found out the way we installed the plugin (at docker container build time) was invalid with how Mautic installs itself (sources tar unarchived in destination, not matter what was the content of destination folder, so plugins were basically removed at runtime).
From what I looked, your container has the same issue, which is why you cannot install the plugin "directly".

We started developing a new function for the Mautic base image to dynamically install plugins:
https://github.com/Monogramm/docker-mautic-base/blob/ee76f627c71dc442edee85c1d2d4cda30dbf4526/common/docker-entrypoint.sh#L105

Right now it is available in both our fork of the base image and the docker-mautic containing the LDAP requirements (and also the plugins now), but it's all still really new so there might be some issues left.

If adding composer in the base image is accepted (mautic/docker-mautic#101), we will throw another PR with this as well. This would allow anyone who uses Mautic docker image to easily install any additional plugins, which I think would be pretty cool ^^

Anyway, back to your configuration issue. The message `LDAP authentication problem` corresponds to the key `mautic.integration.sso.ldapauth.error.authentication_issue` happens when an LDAP connection error is catched:
https://github.com/Monogramm/MauticLdapAuthBundle/blob/d70cd8d29b513293f90703ab80208c9c3a77d97d/Integration/LdapAuthIntegration.php#L138-L148

So there is something wrong with the connection... now you just need to find what.

Normally, in dev mode at `http://your.mautic.instance.com/index_dev.php/s/login`, you should see a bar at the bottom of the screen. This is Symfony debug bar and it should allow you to see all the details of the request, like the logs or where the request went through the app. You can also try to look through the Symofny logs files located at `app/logs`.
If you cannot find some logs of the exception catch, it will be hard to help you...

**Comment by terdinatore** [comment]
Hello @madmath03, 

I also have noticed that all composer instructions during Dockerfile build are not executed in a persistent way. So I executed them after setting up the container with docker exec.

By the way there is something wrong with your composer package. The plugin folder is named MauticLdapauthBundle instead of MauticLdapAuthBundle, which leads to some problem with composer after one has changed it to the right name. I can open another issue if you would like me to.

**Back to Active Directory:** 
I have now a running dev setup using your docker-mautic container version of yesterday. I can access Mautic on index_dev.php and successfully use an OpenLDAP Server for authentication. 
At this point I am also fairly confident that my config is correct as I am able to access both AD and OpenLDAP using ldapsearch on my command line. 

Still I get `LDAP authentication problem; PHP Warning - ldap_bind(): Unable to bind to server: Invalid credentials` what made me assume that there are special quirks to implement AD authentication, especially that all software I use with AD auth, have a boolean switch for AD included (e.g. GitLab or Proxmox).

I could not do more than some googling on AD with symfony/ldap and found out that is definitively possible, but most likely requires extra code. 
It might be that AD does not accept the way you try to bind: 
https://github.com/Monogramm/MauticLdapAuthBundle/blob/d70cd8d29b513293f90703ab80208c9c3a77d97d/Integration/LdapAuthIntegration.php#L128

I have forked your repo now and will try to look some more into that function call.

**Comment by madmath03** [comment]
Regarding the naming issue, I do not see why you would want to rename it because so far I have not seen issues but as you said, it's best that we discuss this in a separate issue.

**Back to Active Directory**
You're probably right that AD requires something special but unfortunately, we do not have an AD to test the behavior and implement this.
I quickly looked up at PHP LDAP doc itself and found this comment mentioning a bind with the form `{$user}@{$domain}`: https://www.php.net/manual/fr/ref.ldap.php#99347
Maybe that's the trick to AD bind in PHP?

Also, the next level for LDAP integration would be to use a "global/technical" bind account, then use this bind account to query the LDAP, find the requested user and check that the password matches the input.
This also provides the possibility to retrieve groups associated to a user.
This can be considered the "objective" of any LDAP integration, but this requires a lot more intelligence and time to develop. I hope this is not the only correct way to interact with an AD...

Those are just hints that I hope may help you to find how to bind to an AD.

**Comment by terdinatore** [comment]
I now have a working Active directory bind by manually inserting credentials, $dn and $query. This means now it is just a matter of parsing the input variables the right way to get everything straight.

There was an issue with case-sensitivity, as LDAP itself is not case-sensitive but string comparing in php is. So I had to change the `sAMAccountname` to `samaccountname` to get the login variable populated.

This is what the modified function looks like at the moment:

```php
try {
                $userKey = $settings['user_key'];
                //$query = $settings['user_query'];
                $query = "samaccountname=Administrator";

                //$dn = "$userKey=$login,$base_dn";
                $dn = "DC=dc,DC=example,DC=com”;
                
		$password = $parameters['password'];

                $ldap->bind("Administrator@dc.example.com”, $password);
                fwrite($stderr, "\n-------------------------LDAP bind successful------------------------");
                $response = $ldap->find($dn, $query);
                // If we reach this far, we expect to have found something
                // and join the settings to the response to retrieve user fields
                fwrite($stderr, "\n-------------------Success search for $query-----------------\n");
                if (is_array($response)) {
                    $response['settings'] = $settings;
                }
``` 
Where Administrator is the requested user.

This means the way you implemented the authentication works for AD, too. I will need some time to implement the different structure and I would be happy if you could show/write me how to implement an boolean Active directory switch to the config in local.php

**Comment by madmath03** [comment]
@terdinatore New release 1.1.0 available with this fix and a few other things: https://github.com/Monogramm/MauticLdapAuthBundle/releases/tag/1.1.0

Thanks a lot for your help with this!
