### ISSUE TITLE
Bundle installed with composer has wrong name

### ISSUE THREAD

**Issue by terdinatore** [Monogramm/MauticLdapAuthBundle#2]
When I install the plugin via `composer require monogramm\mauticldapauthbundle` it places the bundle folder in `__DOC__/plugins/MauticLdapauthBundle` instead of `MauticLdapAuthBundle`.

As Mautic uses these folder names as identifier for a few things this breaks the plugin options in the Web GUI for instance. See: 
<img width="1387" alt="Screenshot 2019-05-01 00 57 34" src="https://user-images.githubusercontent.com/23297252/56998604-20c77400-6bac-11e9-84bc-4a9dc02a2b82.png">

I am not quite sure if the plugins even works at all when not named the right way. 

In dev mode I get this error: 
```
RuntimeException: Case mismatch between loaded and declared class names: MauticPlugin\MauticLdapauthBundle\MauticLdapAuthBundle vs MauticPlugin\MauticLdapAuthBundle\MauticLdapAuthBundle
```

**Comment by madmath03** [comment]
Well, now I understand why I did not see any errors on Windows since it's not case sensitive.

Since `MauticLdapauthBundle` is never directly mentioned in the repository, I'm guessing Composer is automatically generating this name from the composer.json package name `mautic-ldap-auth-bundle`.

Changing the package name should fix the issue but that we also mean to create a new package in packagist. I think I will do it after merging your PR for AD.

By the way, between this and the other PR, I think you more than deserve to be listed in a **Contributors** section in the README, if you do not mind of course.

**Comment by terdinatore** [comment]
That is great news.
I would be happy to be listed as a contributor!

**Comment by madmath03** [comment]
@terdinatore New package available: https://packagist.org/packages/monogramm/mautic-ldap-auth-bundle. Thanks again for your help.
